# Generated by Django 3.2.9 on 2021-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_user_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genre',
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.ManyToManyField(related_name='user_genre', to='movies.Genre'),
        ),
    ]
