# Generated by Django 3.2.9 on 2021-11-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0003_auto_20211117_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='user_genre', to='movies.Genre'),
        ),
    ]
