# Generated by Django 3.2.9 on 2021-11-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genre',
        ),
    ]
